sensor_topic:
    lidar_topic: "points_raw"
    imu_topic: "imu_raw"

slam_mode: 1  # 1: Mapping, 2: Localization

lidar:
    # Velodyne_16, Velodyne_32, Velodyne_64, Ouster_128_os1,
    # LeiShen_16, RoboSense_16, Livox_Avia, Livox_Mid_360, None
    lidar_sensor_type: Velodyne_32
    lidar_point_time_scale: 1.0e-6
    lidar_point_jump_span: 4
    lidar_use_min_distance: 4.0
    lidar_use_max_distance: 1000.0
    lidar_rotation_noise_std: 0.001
    lidar_position_noise_std: 0.01

imu:
    init_acc_bias: 0.0
    init_gyro_bias: 0.0
    acc_noise_std: 0.1
    gyro_noise_std: 0.01
    acc_rw_noise_std: 1.0e-4
    gyro_rw_noise_std: 1.0e-4
    has_orientation: false
    data_searcher_buffer_size: 500

gravity: 9.81

calibration:
    lidar_to_imu: [ 1.0, 0.0, 0.0, 0.0,
                    0.0, 1.0, 0.0, 0.0,
                    0.0, 0.0, 1.0, -0.28,
                    0.0, 0.0, 0.0, 1.0 ]

frontend:
    fusion_opti_iters: 30
    fusion_method: LooseCoupling # LooseCoupling, TightCouplingKF, TightCouplingOptimization

    registration_and_searcher_mode: LoamFull_KdTree
    feature:
        corner_thres: 1.0
        planar_thres: 0.1
        planar_voxel_filter_size: 0.4 # every planar frame
        corner_voxel_filter_size: 0.2 # every corner frame
    registration:
        optimization_iter_num: 30
        local_corner_map_size: 50
        local_planar_map_size: 40
        point_search_thres: 1.0 # 搜索点集中，最远点距离不得超过改值
        line_ratio_thres: 3.0
        point_to_planar_thres: 0.2
        position_converge_thres: 0.01
        rotation_converge_thres: 0.05
        keyframe_delta_distance: 1.0
        keyframe_delta_rotation: 0.2
        local_corner_voxel_filter_size: 0.2 # local corner map
        local_planar_voxel_filter_size: 0.4 # local planar map

system:
    keyframe_delta_distance: 1.0
    keyframe_delta_rotation: 0.2
    enable_loopclosure: true
    enable_visualize_global_map: true
    global_map_visualization_resolution: 0.7
    tile_map_grid_size: 100.0

loopclosure:
    registration_converge_threshold: 1.5
    skip_near_loopclosure_threshold: 100
    skip_near_keyframe_threshold: 100
    candidate_local_map_left_range: 20
    candidate_local_map_right_range: 20
    loopclosure_local_map_left_range: 30
    near_neighbor_distance_threshold: 10.0
