sensor_topic:
    lidar_topic: "/points_raw"
    imu_topic: "/imu_correct"

slam_mode: 1  # 1: Mapping, 2: Localization

lidar:
    # Velodyne_16, Velodyne_32, Velodyne_64, Ouster_128_os1,
    # LeiShen_16, RoboSense_16, Livox_Avia, Livox_Mid_360, None
    lidar_sensor_type: Velodyne_16
    lidar_point_jump_span: 1
    lidar_point_time_scale: 1.0
    lidar_use_min_distance: 2.0
    lidar_use_max_distance: 1000.0
    lidar_rotation_noise_std: 0.005
    lidar_position_noise_std: 0.01

imu:
    has_orientation: true
    data_searcher_buffer_size: 2000

gravity: 9.81

calibration:
    lidar_to_imu: [ 1.0, 0.0, 0.0, 0.0,
                    0.0, 1.0, 0.0, 0.0,
                    0.0, 0.0, 1.0, 0.0,
                    0.0, 0.0, 0.0, 1.0 ]

frontend:
    fusion_opti_iters: 20
    fusion_method: LooseCoupling # LooseCoupling, TightCouplingKF, TightCouplingOptimization

    registration_and_searcher_mode: PointToPlane_IVOX
    feature:
        planar_voxel_filter_size: 0.5
    registration:
        optimization_iter_num: 30
        point_to_planar_thres: 0.1
        position_converge_thres: 0.005
        rotation_converge_thres: 0.001

system:
    keyframe_delta_distance: 1.0 # unit: m
    keyframe_delta_rotation: 0.2 # unit: radian
    enable_loopclosure: true
    enable_visualize_global_map: true
    global_map_visualization_resolution: 0.5
    tile_map_grid_size: 100.0

loopclosure:
    registration_converge_threshold: 2.5
    skip_near_loopclosure_threshold: 100
    skip_near_keyframe_threshold: 100
    candidate_local_map_left_range: 30
    candidate_local_map_right_range: 30
    loopclosure_local_map_left_range: 20
    near_neighbor_distance_threshold: 10.0